### ISSUE TITLE
orderId type from int to string in protocol requests

### ISSUE THREAD

**Issue by ergosarapu** [renekorss/Banklink#14]
## Expected Behavior
orderId parameter to accept string in protocol requests so that more unique identifiers could be provided and therefore reducing the probablity of collisions.

## Actual Behavior
Currently orderId parameter accepts only int and this somewhat limits the usage of unique order identifiers to max int size.

I am not sure if current integer orderId is somehow influenced by the underlaying protocol specifications or integration specifics to specific bank, but if string orderId works with all the banks it should be allowed to set string orderId's.

**Comment by renekorss** [comment]
See #10
