### ISSUE TITLE
Problem of PHP 7.0 version support

### ISSUE THREAD

**Issue by peter279k** [renekorss/Banklink#17]
## Expected Behavior
- It should be worked on `php-7.0` version.

## Actual Behavior
- It should be failed on `php-7.0` version.

One of error message is as follows on `php-7.0` version:

```
PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /data/Banklink/src/Banklink.php on line 166
```

## Possible solution
- I think it should let package require `php-7.1` version at least.

**Comment by renekorss** [comment]
Yes, support for PHP 7.0 should be dropped. Please submit PR to fix this issue.
