### ISSUE TITLE
Swedbank LT doesn't include VK_RETURN into mac

### ISSUE THREAD

**Issue by abejingas** [renekorss/Banklink#19]
## Expected Behavior
for swedbank lt mac calculation VK_RETURN should not be included at least for PAYMENT_REQUEST_2001

## Actual Behavior
it is included into calculation, and bank returns an error

## Steps to Reproduce the Problem

  1. make a payment request 
  2.submit to swedbank

**Comment by renekorss** [comment]
Thanks for reporting. It seems that SEB is same. Only Siaulius uses never protocol. Will investigate and fix it.

**Comment by renekorss** [comment]
@abejingas Could you test it and let mw know if it really is fixed?

`composer require renekorss/Banklink:dev-3.x-dev`
