### ISSUE TITLE
PaymentResponse::setAutomatic is not part of the ResponseInterface

### ISSUE THREAD

**Issue by koosh** [renekorss/Banklink#21]
This is not a bug or breaking issue, I just ran into this when the auto-complete did not show isAutomatic as an option.

Method ```\RKD\Banklink\Response\PaymentResponse::isAutomatic``` is not part of the ```\RKD\Banklink\Response\ResponseInterface```

I understand this is because ```AuthResponse``` and ```PaymentResponse``` are different and ```\RKD\Banklink\Banklink::handleResponse``` returns ```ResponseInterface```. But at this point it's up to the developer to know if there is a method setAutomatic on the response instance or do an instanceof check:
```php

            if ($response instanceof PaymentResponse && $response->isAutomatic()) {
                ...
            }

```

I see two solutions:
1. Add the isAutomatic to the current interface and in case of AuthResponse always return false.
2. Extend ResponseInterface with PaymentResponseInterface which adds isAutomatic and change handleResponse

Just something to consider, I would consider making the changes if the author thinks this as something worthwhile of doing.

**Comment by renekorss** [comment]
Thanks for reporting and noticing. I would be glad if you would make PR. Please use first solution, since it feels cleaner and more logical to me.
I will mark you as assignee, let me know if it's not okay with you.

**Comment by koosh** [comment]
Upon further looking there's many different public methods both AuthResponse and PaymentResponse provide, that are not part of the interface. And it looks like there are very clear use cases (auth and payment) that require different interfaces. Changes for the sake of change are not something this package needs, its working just fine. So I'll leave it as it is.

**Comment by renekorss** [comment]
Thanks for looking into it!
