### ISSUE TITLE
New Luminor banklink

### ISSUE THREAD

**Issue by rang501** [renekorss/Banklink#30]
Luminor has changed its website and banklink URLs.

Details about it are here: https://luminor.ee/banklink-requests-technical-specification#requests

Is anyone working on it already?

**Comment by renekorss** [comment]
Since you already made the changes, could you send me PR?

**Comment by rang501** [comment]
Yes, I tried to start with something as this is something I need a bit faster.

I think changing banklink URLs is enough.
There are GET and POST related changes but this isn't affecting this library.
