### ISSUE TITLE
Rename banks

### ISSUE THREAD

**Issue by renekorss** [renekorss/Banklink#4]
Rename old class names to new:

- Krediidipank to Coop Pank

Duplicate:

- Nordea to Luminor (Luminor only exists in Baltics)

**Comment by orukaz** [comment]
Hey,

How far is the v3.0 ?

Raido

**Comment by renekorss** [comment]
Not far at all. I'm currently working on testing Pocopay with their staff. If that gets done, I'll do some more review and release v3.0.

I believe it to happen in this month.

**Comment by orukaz** [comment]
Hey,

Very cool ;) Waiting ;)

Raido

**Comment by renekorss** [comment]
Pocopay testing done. All works well.
