### ISSUE TITLE
Banklink implementation sets VK_REF and VK_MSG even if LtSwedbank specification allows only one of the fields to be used

### ISSUE THREAD

**Issue by zexa** [renekorss/Banklink#53]
Normally this isn't an issue, however, if you want to use LtSEB via LtSwedbank (spec allows it by changing the request URL), Swedbank will throw an error such as this:

![index](https://user-images.githubusercontent.com/544787/116521985-514a6180-a8dd-11eb-890b-802f57f5b57f.png)

This requirement is specified in the Swedbank specification in https://www.swedbank.lt/static/pdf/business/banklink_technines_specifikacijos_LT_2020-08-07.pdf however it is not mentioned in the English spec. I assume this is because using other banks via LtSwed is a LtSwed only feature.

See request 1002 specs which near `VK_REF` says 
> Mokėjimo pavedimo įmokos kodas. Šio lauko negalima naudoti, jei naudojamas VK_MSG.

Which roughly translates to 
> Payment transfer code. This field cannot be used if VK_MSG is used.

The lib user should be provided with a way to control the fields sensibly before creating the finalized form. Specifically, I'd like the ability to set VK_REF to null, in which case the VK_REF field would not be included in VK_MAC and the data itself.

## Steps to Reproduce the Problem

  1. Create LtSwedbank payment
  2. Change URL to `https://banklink.swedbank.com/LT/CBVILT2X`
  3. Redirect user for payment
  4. See error as shown above

## Specifications

  - Version: `"renekorss/banklink": "^3.3"`
  - Platform: Symfony 4.4

**Comment by zexa** [comment]
I tried to overwrite both `VK_REF` and `VK_MSG` via `$customRequestData` inside `getPaymentRequest` from `RKD\Banklink\Banklink` , however that causes an `UnexpectedValueException` that says
> Field VK_MSG must be set to use service 1002.

**Comment by renekorss** [comment]
Thanks for reporting. I will take a look into this. Since I'm quite busy right now, it could take me some time. Probably this week.

**Comment by zexa** [comment]
Any updates? Let me know if there's something I can help with.

**Comment by renekorss** [comment]
I researched this a bit and to my understanding setting `VK_MSG` to empty string (`''`) is actually what's needed. This is because it still needs to be in `VK_MAC`. At least what I can see from examples from documentation. I found english version here: https://www.swedbank.lt/files/Banklink_TC_en.pdf

Using empty string won't throw `UnexpectedValueException` since it is set, is not `false` and is not `null`. Have you tried this? If not, please do and let me know.

**Comment by zexa** [comment]
Hi, apologies for the delayed response. 

All I get is an invalid VK_MAC if I leave VK_MSG empty. I haven't taken the time to debug the generated VK_MAC before encoding it but my guess would be that leaving VK_MSG generates a `000` signature string.

**Comment by renekorss** [comment]
From this document, `000` is exactly what it should generate. View start of last page.

**Comment by zexa** [comment]
> Is bank replying with message that VK_MAC is invalid?

Yep.

**Comment by zexa** [comment]
The project I'm currently working on is not yet publicly available and even if it was you'd need to meet special conditions in order to get an account in it.

Long story short I don't think I can give you access to a testing environment. I'd have to consult my employer and I don't think he'd be too happy with the idea.

Perhaps if you told me what you're looking for I could do the experiments for you?

**Comment by renekorss** [comment]
Completely understand. Does bank have test environment I could play with?

**Comment by zexa** [comment]
From what I see in https://www.swedbank.lt/business/cash/banklink/paymentPortal Swedbank does not have a sandbox.

**Comment by zexa** [comment]
I suppose I could look into opening an account for a personal project.

**Comment by renekorss** [comment]
For debuging, please uncomment this line https://github.com/renekorss/Banklink/blob/2a9501559fc531fcaee159d79c74b66846511435/src/Protocol/IPizza/Services2015.php#L101 and try to overwrite VK_REF in data by setting it to null.
Let's see of it then passes.
